package org.example.enumeration;

public enum ObjectivePoints {
    QUILL, MANUSCRIPT, INKWELL, CORNER, FUNGI, ANIMAL, PLANT, INSECT, REDDIAG, GREENDIAG, BLUDIAG, PURPLEDIAG,REDGREEN, GREENPURPLE, BLUERED, PURPLEBLUE
}
